## 二维卷积代码演示

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from math import floor

定义常量

In [2]:
in_channels = 1
out_channels = 1
kernel_size = 3
batch_size = 1
bias = False
input_size = [batch_size, in_channels, 4, 4]

In [3]:
conv_layer = nn.Conv2d(in_channels, out_channels, kernel_size, bias=bias)
input_feature_map = torch.randn(input_size)
output_feature_map = conv_layer(input_feature_map)

print(input_feature_map)
print(conv_layer.weight)
print('conv shape: ', conv_layer.weight.shape)  # out_channels * in_channels * height * width
print(output_feature_map)

tensor([[[[-0.1155,  1.4302, -0.3380,  2.3349],
          [ 0.3045,  0.2451, -0.1641, -0.0408],
          [ 0.8828,  0.8284,  0.1857, -3.7096],
          [ 0.3694, -0.7512, -0.5036, -0.3607]]]])
Parameter containing:
tensor([[[[ 0.1958, -0.0813, -0.1376],
          [-0.0529,  0.3282,  0.0298],
          [-0.2797, -0.2688, -0.1258]]]], requires_grad=True)
conv shape:  torch.Size([1, 1, 3, 3])
tensor([[[[-0.5260,  0.1033],
          [ 0.4550,  0.3645]]]], grad_fn=<ConvolutionBackward0>)


In [4]:
output_feature_map1  = F.conv2d(input_feature_map, conv_layer.weight)
print(output_feature_map1)

tensor([[[[-0.5260,  0.1033],
          [ 0.4550,  0.3645]]]], grad_fn=<ConvolutionBackward0>)


### 实现卷积

In [5]:
input = torch.randn(5, 5)  # 卷积输入特征图
kernel = torch.randn(3, 3)  # 卷积核
bias = torch.randn(1)  # 卷积偏置 默认输出通道数目为1

print(input)
print(kernel)
print(bias)

tensor([[ 0.9505, -0.4460,  0.8429, -0.3798,  0.3851],
        [-0.5468,  0.6040, -0.1081, -1.4094,  0.1884],
        [ 0.8526, -1.2893,  0.6167,  1.2525, -0.3472],
        [ 0.8868,  1.3822,  0.3365, -0.6784, -0.1037],
        [-1.0550,  1.7445, -0.1075,  1.1560,  0.2925]])
tensor([[-0.0231,  0.1776,  0.7969],
        [ 1.8381,  1.8153,  0.3973],
        [-0.6080, -1.4425,  0.7053]])
tensor([-1.2711])


用原始的矩阵运算实现二维卷积

先不考虑batch_size维度和channel维度

In [6]:
def matrix_multiplication_for_conv2d(input, kernel, bias=0, stride=1, padding=0):
    if padding > 0:
        input = F.pad(input, (padding, padding, padding, padding))

    input_h, input_w = input.shape
    kernel_h, kernel_w = kernel.shape

    output_h = floor((input_h - kernel_h) / stride + 1)  # 卷积输入的高度
    output_w = floor((input_w - kernel_w) / stride + 1)  # 卷积输入的宽度
    output = torch.zeros(output_h, output_w)  # 初始化输出矩阵
    for i in range(0, input_h - kernel_h + 1, stride):  # 对高度进行遍历
        for j in range(0, input_w - kernel_w + 1, stride):  # 对宽度进行遍历
            region = input[i:i + kernel_h, j:j + kernel_h]  # 取出被核滑动到的区域
            output[int(i / stride), int(j / stride)] = torch.sum(region * kernel) + bias  # 点乘 并赋值给输出位置的元素

    return output

结果验证：

In [7]:
# 矩阵运算实现卷积的结果
mat_mul_conv_output = matrix_multiplication_for_conv2d(input, kernel, bias=bias, padding=1, stride=2)
print(mat_mul_conv_output)

# 调用pytorch api卷积的结果
pytorch_api_conv_output = F.conv2d(input.reshape(1, 1, input.shape[0], input.shape[1]),
                                   kernel.reshape(1, 1, kernel.shape[0], kernel.shape[1]),
                                   padding=1,
                                   bias=bias,
                                   stride=2)
print(pytorch_api_conv_output.squeeze())

torch.allclose(mat_mul_conv_output, pytorch_api_conv_output)  # 验证成功

tensor([[ 1.4919, -1.9171, -0.6849],
        [-0.1557, -4.9845,  1.0292],
        [-1.2342,  1.6869,  1.3821]])
tensor([[ 1.4919, -1.9171, -0.6849],
        [-0.1557, -4.9845,  1.0292],
        [-1.2342,  1.6869,  1.3821]])


True

region拉直, flatten版本:

In [8]:
def matrix_multiplication_for_conv2d_flatten(input, kernel, bias=0, stride=1, padding=0):
    if padding > 0:
        input = F.pad(input, (padding, padding, padding, padding))

    input_h, input_w = input.shape
    kernel_h, kernel_w = kernel.shape

    output_h = floor((input_h - kernel_h) / stride + 1)  # 卷积输入的高度
    output_w = floor((input_w - kernel_w) / stride + 1)  # 卷积输入的宽度
    output = torch.zeros(output_h, output_w)  # 初始化输出矩阵

    region_matrix = torch.zeros(output.numel(), kernel.numel())  # 存储着拉平后的所有特征区域
    kernel_matrix = kernel.reshape(kernel.numel(), 1)  # kernel的列向量（矩阵）形式
    row_index = 0
    for i in range(0, input_h - kernel_h + 1, stride):  # 对高度进行遍历
        for j in range(0, input_w - kernel_w + 1, stride):  # 对宽度进行遍历
            region = input[i:i + kernel_h, j:j + kernel_h]  # 取出被核滑动到的区域
            region_vector = torch.flatten(region)
            region_matrix[row_index] = region_vector
            row_index += 1

    output_matrix = region_matrix @ kernel_matrix
    output = output_matrix.reshape(output_h, output_w) + bias

    return output

In [9]:
# flatten版 实现卷积的结果
mat_mul_conv_output_flatten = matrix_multiplication_for_conv2d_flatten(input, kernel, bias=bias, padding=1, stride=2)
print(mat_mul_conv_output_flatten)

# 调用pytorch api卷积的结果
pytorch_api_conv_output = F.conv2d(input.reshape(1, 1, input.shape[0], input.shape[1]),
                                   kernel.reshape(1, 1, kernel.shape[0], kernel.shape[1]),
                                   padding=1,
                                   bias=bias,
                                   stride=2)
print(pytorch_api_conv_output.squeeze())

torch.allclose(mat_mul_conv_output_flatten, pytorch_api_conv_output)  # 验证成功

tensor([[ 1.4919, -1.9171, -0.6849],
        [-0.1557, -4.9845,  1.0292],
        [-1.2342,  1.6869,  1.3821]])
tensor([[ 1.4919, -1.9171, -0.6849],
        [-0.1557, -4.9845,  1.0292],
        [-1.2342,  1.6869,  1.3821]])


True

考虑batch_size维和channel维度的完整实现

In [10]:
def matrix_multiplication_for_conv2d_full(input, kernel, bias=None, stride=1, padding=0):
    # input, kernel都是四维的张量
    if padding > 0:
        input = F.pad(input, (padding, padding, padding, padding, 0, 0, 0, 0))

    bs, in_channel, input_h, input_w = input.shape
    output_channel, in_channel, kernel_h, kernel_w = kernel.shape

    if bias is None:
        bias = torch.zeros(output_channel)

    output_h = floor((input_h - kernel_h) / stride + 1)  # 卷积输入的高度
    output_w = floor((input_w - kernel_w) / stride + 1)  # 卷积输入的宽度
    output = torch.zeros(bs, output_channel, output_h, output_w)  # 初始化输出矩阵

    for idx in range(bs):
        for oc in range(output_channel):
            for ic in range(in_channel):
                for i in range(0, input_h - kernel_h + 1, stride):  # 对高度进行遍历
                    for j in range(0, input_w - kernel_w + 1, stride):  # 对宽度进行遍历
                        region = input[idx, ic, i:i + kernel_h, j:j + kernel_h]  # 取出被核滑动到的区域
                        output[idx, oc, int(i / stride), int(j / stride)] += torch.sum(region * kernel[oc, ic])  # 点乘 并赋值给输出位置的元素
            output[idx, oc] += bias[oc]

    return output

In [11]:
input = torch.randn(2 ,2, 5, 5)  # bs * in_channel * in_h * in_w
kernel = torch.randn(3, 2, 3, 3)  # out_channel * in_channel * kernel_h * kernel_w
bias = torch.randn(3)

pytorch_conv2d_api_output = F.conv2d(input, kernel, bias, padding=1, stride=2)
mm_conv2d_full_output = matrix_multiplication_for_conv2d_full(input, kernel, bias=bias, padding=1, stride=2)

torch.allclose(mm_conv2d_full_output, pytorch_conv2d_api_output)

True

对kernel进行展开来实现二维卷积 并推导出转置卷积: 先不考虑batch和channel, 不考虑padding, 假设stride=1

In [12]:
def get_kernel_matrix(kernel, input_size):
    """ 基于kernel和输入特征图的大小来得到填充拉直后的kernel堆叠后的矩阵 """
    kernel_h, kernel_w = kernel.shape
    input_h, input_w = input_size
    num_out_feat_map = (input_h - kernel_h + 1) * (input_w - kernel_w + 1)
    result = torch.zeros(num_out_feat_map, input_h * input_w)  # 初始化结果矩阵 输出特征图元素个数 * 输入特征图元素个数
    count = 0
    for i in range(0, input_h - kernel_h + 1, 1):
        for j in range(0, input_w - kernel_w + 1, 1):
            padded_kernel = F.pad(kernel, (i, input_h - kernel_h - i, j, input_w - kernel_w - j))  # 填充成跟输入特征图一样大小
            result[count] = padded_kernel.flatten()
            count += 1

    return result

In [13]:
kernel = torch.randn(3, 3)
input = torch.randn(4, 4)
kernel_matrix = get_kernel_matrix(kernel, input.shape)  # 4*16

print(kernel)
print(kernel_matrix)

tensor([[-1.5272, -2.5173,  0.9265],
        [ 1.3476,  0.5256,  1.2691],
        [-0.4085, -1.0632, -1.3741]])
tensor([[-1.5272, -2.5173,  0.9265,  0.0000,  1.3476,  0.5256,  1.2691,  0.0000,
         -0.4085, -1.0632, -1.3741,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -1.5272, -2.5173,  0.9265,  0.0000,
          1.3476,  0.5256,  1.2691,  0.0000, -0.4085, -1.0632, -1.3741,  0.0000],
        [ 0.0000, -1.5272, -2.5173,  0.9265,  0.0000,  1.3476,  0.5256,  1.2691,
          0.0000, -0.4085, -1.0632, -1.3741,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -1.5272, -2.5173,  0.9265,
          0.0000,  1.3476,  0.5256,  1.2691,  0.0000, -0.4085, -1.0632, -1.3741]])


验证二维卷积

In [14]:
mm_conv2d_output = kernel_matrix @ input.reshape(-1, 1)
pytorch_conv2d_output = F.conv2d(input.unsqueeze(0).unsqueeze(0), kernel.unsqueeze(0).unsqueeze(0))

print(mm_conv2d_output)
print(pytorch_conv2d_output)

tensor([[-2.2367],
        [ 0.3064],
        [-2.1816],
        [ 3.5625]])
tensor([[[[-2.2367, -2.1816],
          [ 0.3064,  3.5625]]]])


验证二维转置卷积

In [15]:
mm_transposed_conv2d_output = kernel_matrix.transpose(-1, -2) @ mm_conv2d_output
pytorch_transposed_conv2d_output = F.conv_transpose2d(pytorch_conv2d_output, kernel.unsqueeze(0).unsqueeze(0))

print(mm_transposed_conv2d_output.reshape(4, 4))
print(pytorch_transposed_conv2d_output)

tensor([[  3.4159,   8.9621,   3.4194,  -2.0213],
        [ -3.4821, -10.3277, -12.6691,   0.5322],
        [  1.3266,   8.2311,   7.6543,   7.5188],
        [ -0.1252,  -1.7810,  -4.2088,  -4.8953]])
tensor([[[[  3.4159,   8.9621,   3.4194,  -2.0213],
          [ -3.4821, -10.3277, -12.6691,   0.5322],
          [  1.3266,   8.2311,   7.6543,   7.5188],
          [ -0.1252,  -1.7810,  -4.2088,  -4.8953]]]])
