## 二维卷积代码演示

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

定义常量

In [2]:
in_channels = 1
out_channels = 1
kernel_size = 3
batch_size = 1
bias = False
input_size = [batch_size, in_channels, 4, 4]

In [3]:
conv_layer = nn.Conv2d(in_channels, out_channels, kernel_size, bias=bias)
input_feature_map = torch.randn(input_size)
output_feature_map = conv_layer(input_feature_map)

print(input_feature_map)
print(conv_layer.weight)
print('conv shape: ', conv_layer.weight.shape)  # out_channels * in_channels * height * width
print(output_feature_map)

tensor([[[[-1.6169,  1.8670, -0.6947, -0.0660],
          [-0.7948,  0.9490,  2.0414, -0.8899],
          [ 0.0791, -1.1917,  0.7667, -1.1554],
          [ 0.8859, -0.7373,  0.7868,  0.0789]]]])
Parameter containing:
tensor([[[[-0.3258,  0.0586,  0.0465],
          [ 0.1688,  0.1298, -0.1260],
          [ 0.2051, -0.2286,  0.1546]]]], requires_grad=True)
conv shape:  torch.Size([1, 1, 3, 3])
tensor([[[[ 0.7428, -0.7131],
          [ 0.6435, -0.5058]]]], grad_fn=<ConvolutionBackward0>)


In [4]:
output_feature_map1  = F.conv2d(input_feature_map, conv_layer.weight)
print(output_feature_map1)

tensor([[[[ 0.7428, -0.7131],
          [ 0.6435, -0.5058]]]], grad_fn=<ConvolutionBackward0>)
