In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [5]:
# batch_size, seqlen, vocab_size
logits = torch.randn(2, 3, 4)
label = torch.randint(0, 4, (2, 3))

logits = logits.transpose(1, 2)
F.cross_entropy(logits, label, reduction='none')

tensor([[2.4129, 1.2032, 1.6791],
        [1.0048, 0.9689, 2.1638]])

In [14]:
tgt_len = torch.tensor([2, 3], dtype=torch.int32)
mask = torch.stack([F.pad(torch.ones(L), (0, max(tgt_len - L))) for L in tgt_len])
mask

tensor([[1., 1., 0.],
        [1., 1., 1.]])

In [13]:
F.cross_entropy(logits, label, reduction='none') * mask

tensor([[2.4129, 1.2032, 0.0000],
        [1.0048, 0.9689, 2.1638]])

In [16]:
print(label)
label[0, 2] = -100
print(label)
# ignore_index: int = -100,
F.cross_entropy(logits, label, reduction='none')

tensor([[1, 1, 0],
        [1, 1, 0]])
tensor([[   1,    1, -100],
        [   1,    1,    0]])


tensor([[2.4129, 1.2032, 0.0000],
        [1.0048, 0.9689, 2.1638]])