# 自定义层

构造一个没有任何参数的自定义层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

将层作为组件合并到更复杂的模型中

In [2]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(3.7253e-09, grad_fn=<MeanBackward0>)

带参数的层

In [3]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.1448, -0.2720,  0.8136],
        [ 0.3505, -0.1864, -1.2959],
        [ 1.7051,  1.4514,  0.7479],
        [-0.0625,  0.4423, -0.4311],
        [ 1.9631, -0.0054,  2.1797]], requires_grad=True)

使用自定义层直接执行前向传播计算

In [7]:
linear(torch.rand(2, 5))

tensor([[0.0984, 0.5687, 2.8316],
        [2.2558, 0.0000, 1.8880]])

使用自定义层构建模型

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[7.5465],
        [4.6817]])