<a href="https://colab.research.google.com/github/PacktPublishing/Hands-On-Computer-Vision-with-PyTorch/blob/master/Chapter02/Initializing_a_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 2.2.1 初始化张量

书中P33

In [1]:
# 导入PyTorch并通过调用torch.tensor在列表中初始化一个张量
import torch

x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [2]:
# 访问张量对象的形状和数据类型
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [3]:
# 张量内所有元素的数据类型是相同的 这就意味着如果一个张量包含不同数据类型的数据(比如布尔、整数和浮点数)
# 那么整个张量会被强制转换为一种最为通用的数据类型
x = torch.tensor([False, 1, 2.0])
print(x)
# tensor([0., 1., 2.])

tensor([0., 1., 2.])


In [4]:
# 生成一个张量对象, 它有三行四列, 填充0
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
# 生成一个张量对象, 它有三行四列, 填充1
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
# 生成一个张量对象, 它有三行四列, 生成的值介于0和10之间(包含小值但不包括大值)
torch.randint(low=0, high=10, size=(3,4))

tensor([[8, 6, 8, 7],
        [0, 2, 1, 2],
        [8, 6, 6, 8]])

In [7]:
# 生成具有0和1之间随机数的三行四列的张量
torch.rand(3, 4)

tensor([[0.4468, 0.0776, 0.2071, 0.7695],
        [0.6584, 0.4347, 0.5693, 0.7163],
        [0.8118, 0.2063, 0.9942, 0.2635]])

In [8]:
# 生成数值服从正态分布的三行四列的张量
torch.randn((3,4))

tensor([[ 1.1459,  0.1504, -2.5967,  1.3636],
        [-0.7218,  0.2458, -0.3939, -1.6656],
        [-0.4448, -2.4501, -0.2307, -1.5707]])

In [9]:
import numpy as np

# 可以直接使用torch.tensor(<Numpy-array>)将NumPy数组转换为Torch张量
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))


<class 'numpy.ndarray'> <class 'torch.Tensor'>
